# list_of_indian_state_abbreviation
indian_state_abbreviation = {
    'AN' : 'Andaman and Nicobar Islands',
    'AP' : 'Andhra Pradesh',
    'AR' : 'Arunachal Pradesh',
    'AS' : 'Assam',
    'BR' : 'Bihar',
    'CG' : 'Chhattisgarh',
    'CH' : 'Chandigarh',
    'DD' : 'Daman and Diu',
    'DH' : 'Dadra and Nagar Haveli',
    'DL' : 'Delhi',
    'GA' : 'Goa',
    'GJ' : 'Gujarat',
    'HR' : 'Haryana',
    'HP' : 'Himachal Pradesh',
    'JK' : 'Jammu and Kashmir',
    'JH' : 'Jharkhand',
    'KA' : 'Karnataka',
    'KL' : 'Kerala',
    'LD' : 'Lakshadweep',
    'MP' : 'Madhya Pradesh',
    'MH' : 'Maharashtra',
    'MN' : 'Manipur',
    'ML' : 'Meghalaya',
    'MZ' : 'Mizoram',
    'NL' : 'Nagaland',
    'OR' : 'Odisha',
    'PB' : 'Punjab',
    'PY' : 'Puducherry',
    'RJ' : 'Rajasthan',
    'SK' : 'Sikkim',
    'TN' : 'Tamil Nadu',
    'TG' : 'Telangana',
    'TR' : 'Tripura',
    'UK' : 'Uttarkhand',
    'UP' : 'Uttar Pradesh',
    'WB' : 'West Bengal',
}
